apis/urls.py
from django.urls import path
from apis.v1 import UserCreateView, UserLoginView, UserLogoutView, UserGetView, RelationCreateView, RelationDeleteView

urlpatterns = [    
    path('v1/users/login/', UserLoginView.as_view(), name='apis_v1_user_login'),
    path('v1/users/logout/', UserLogoutView.as_view(), name='apis_v1_user_logout'),
    path('v1/users/create/', UserCreateView.as_view(), name='apis_v1_user_create'),
    path('v1/users/get/', UserGetView.as_view(), name='apis_v1_user_get'),
    path('v1/relations/create/', RelationCreateView.as_view(), name='apis_v1_relation_create'),
    path('v1/relations/delete/', RelationDeleteView.as_view(), name='apis_v1_relation_delete'),
]

config/urls.py
from pipes import Template
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.conf import settings

from contents.views import HomeView, RelationView
from apis.v1 import RelationCreateView
from contents.models import Status

admin.site.site_header = "DevBox Admin"
admin.site.site_title = "DevBox Admin Site"
admin.site.index_title = "Hello everyone:)"
admin.site.register(Status)


class NonUserTemplateView(TemplateView):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_anonymous:
            return redirect('contents_home')
        return super(NonUserTemplateView, self).dispatch(request, *args, **kwargs)
    

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', HomeView.as_view(), name='contents_home'),
    path('login/', NonUserTemplateView.as_view(template_name='login.html'), name='login'),
    path('register/', NonUserTemplateView.as_view(template_name='register.html'), name='register'),
    path('relation/', RelationView.as_view(), name='contents_relation'),
    
    path('apis/', include('apis.urls')),
    path("home/", include('devbox.urls')),
]


urlpatterns += [
    path('accounts/', include('allauth.urls'))
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

devbox/urls.py
from .Views import views, searchViews, deleteViews, mailingViews
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

app_name = "devbox"

urlpatterns = [
    path("", login_required(views.home), name="home"),  # home directory
    path("<int:pk>/", views.change_directory,
         name="changeDirectory"),  # 디렉토리 이동

    path("uploadFile/<int:pk>/", views.uploadFile, name="uploadFile"),  # 파일 업로드
    path("downloadFile/<int:pk>/", views.downloadFile,
         name="downloadFile"),  # 파일 다운로드
    path("createFolder/<int:pk>/", views.createFolder,
         name="createFolder"),  # 폴더 생성
    path("deleteFileAndFolder/<int:pk>/", views.deleteFileAndFolder,
         name="deleteFileAndFolder"),  # 파일 및 폴더 삭제
    path("renameFileAndFolder/<int:pk>/", views.renameFileAndFolder,
         name="renameFileAndFolder"),  # 파일 및 폴더 이름 수정
    path("sortFileAndFolder/<int:pk>/", views.sortFileAndFolder,
         name="sortFileAndFolder"),  # 파일 정렬

    path("search/", login_required(searchViews.searchFileAndFolder), name="search"),
    path("sh/<uuid:uuid>/", mailingViews.display_file_and_folder_ui, name='shared'),
    path("s/<uuid:uuid>/", mailingViews.display_file_and_folder_ui,
         name='shared_file'),  # 파일 공유
    path("mailing/", mailingViews.mailing, name="mailing"),  # 메일링

    path("recyclebin/", deleteViews.recyclebin,
         name="recyclebinDisplay"),  # 휴지통
    path("recyclebin/<int:pk>", deleteViews.changeDirectoryInRecyclebin,
         name="changeDirectoryInRecyclebin"),  # 휴지통 내 폴더 이동
    path("restore/<int:pk>", deleteViews.restore, name="restore"),  # 파일 및 폴더 복구
    path("permanentDelete/<int:pk>", deleteViews.permanentDelete,
         name="permanentDelete"),  # 파일 및 폴더 영구
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

django_base/django_base/urls.py
from pipes import Template
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.conf import settings

from contents.views import HomeView, RelationView

admin.site.site_header = "Fastgram Admin"
admin.site.site_title = "Fastgram Admin Site"
admin.site.index_title = "Hello everyone:)"


class NonUserTemplateView(TemplateView):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_anonymous:
            return redirect('contents_home')
        return super(NonUserTemplateView, self).dispatch(request, *args, **kwargs)
    

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', HomeView.as_view(), name='contents_home'),
    path('login/', NonUserTemplateView.as_view(template_name='login.html'), name='login'),
    path('register/', NonUserTemplateView.as_view(template_name='register.html'), name='register'),
    path('relation/', RelationView.as_view(), name='contents_relation'),
    path('apis/', include('apis.urls')),
]


urlpatterns += [
    path('accounts/', include('allauth.urls'))
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

devbox/models.py
import os.path
from django.db import models
from django.utils.timezone import now
import uuid


class Folder(models.Model):
    userName = models.CharField(max_length=100, null=True)
    folderName = models.CharField(max_length=100, default=now().strftime("%Y%m%d%H%M%S"))
    dateTimeOfUpload = models.DateTimeField(auto_now=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name="child_folder", null=True, blank=True)
    uuid = models.UUIDField(default=uuid.uuid4, unique=True)

    def get_foldername(self):
        return self.folderName


class Files(models.Model):
    userName = models.CharField(max_length=100, null=True)
    fileName = models.CharField(max_length=100, default=now().strftime("%Y%m%d%H%M%S"))
    fileSize = models.IntegerField(default=0)
    uploadedFile = models.FileField(upload_to="UploadedFiles/")
    dateTimeOfUpload = models.DateTimeField(auto_now=True)
    parent = models.ForeignKey(Folder, on_delete=models.CASCADE, related_name="child_files", null=True, blank=True)
    uuid = models.UUIDField(default=uuid.uuid4, unique=True)

    def get_filename(self):
        return os.path.basename(self.uploadedFile.url)

    def delete(self, *args, **kwargs):
        super(Files, self).delete(*args, **kwargs)
        self.uploadedFile.delete()


class RecycleBins(models.Model):
    deletedFolderID = models.ForeignKey(
        Folder, on_delete=models.CASCADE, related_name="deleted_folder", null=True, blank=True)
    deletedFileID = models.ForeignKey(
        Files, on_delete=models.CASCADE, related_name="deleted_files", null=True, blank=True)
    dateTimeOfDelete = models.DateTimeField(auto_now=True)

devbox/Views/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.db.models import Q
from devbox.models import Files, Folder, RecycleBins
from contents.models import Bucket
from .utilsViews import sort, download
import boto3


s3 = boto3.client('s3',
                  aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
                  aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY)


def get_bucket(request):
    bucketName = Bucket.objects.get(userName=request.user).bucketName
    return bucketName


# Get parent folder name
def get_parent_folder_name(pk):
    parent_folders = []
    current_folder = Folder.objects.filter(id=pk if pk != 0 else None)
    while len(current_folder) > 0:
        parent_folders.insert(0, {"id": current_folder[0].id, "folderName": current_folder[0].folderName})
        if current_folder[0].parent_id is not None:
            current_folder = Folder.objects.filter(id=current_folder[0].parent_id)
        else:
            current_folder = []
    return parent_folders


# display file / folder
def display_file_and_folder(request, pk):
    get_bucket(request)
    q = Q()
    q &= Q(userName=request.user)
    q &= Q(parent_id=pk if pk != 0 else None)

    files = list(Files.objects.filter(q).order_by("fileName"))
    folders = list(Folder.objects.filter(q).order_by("folderName"))

    not_deleted_files = []
    for file in files:
        if len(file.deleted_files.all()) == 0:
            not_deleted_files.append(file)

    not_deleted_folders = []
    for folder in folders:
        if len(folder.deleted_folder.all()) == 0:
            not_deleted_folders.append(folder)

    return render(request, "home.html", context={
        "current_folder_id": pk,
        "files": not_deleted_files,
        "folders": not_deleted_folders,
        "parentFolders": get_parent_folder_name(pk),
    })


# home directory
def home(request):
    return display_file_and_folder(request, 0)


# change directory
def change_directory(request, pk):
    return display_file_and_folder(request, pk)


# 파일 업로드
@csrf_exempt
def uploadFile(request, pk):
    if request.method == "POST":
        for selected in request.FILES.getlist("file"):
            if len(selected) >= 1:
                q = Q()
                q &= Q(userName=request.user)
                q &= Q(fileName=selected.name)
                q &= Q(parent_id=pk if pk != 0 else None)
                duplicated_file = Files.objects.filter(q)

                if len(duplicated_file) == 0:
                    file = Files(
                        userName=request.user,
                        uploadedFile=selected,
                        fileName=selected.name,
                        fileSize=selected.size,
                        parent_id=pk if pk != 0 else None,
                    )
                    file.save()
                    s3.upload_fileobj(selected, get_bucket(request), str(file.uuid))

            elif len(selected) < 1:
                print("업로드 할 파일을 선택해 주세요")

    return redirect("devbox:changeDirectory", pk)


# 파일 다운로드
@csrf_exempt
def downloadFile(request, pk):
    if request.method == "POST":
        selected = request.POST.getlist("selected_file")

        # 파일 다운로드
        if len(selected) >= 1:
            download(request, selected)

        # 파일 선택 안함 예외 처리
        elif len(selected) < 1:
            print("다운로드할 파일을 선택해 주세요")
    return redirect("devbox:changeDirectory", pk)


# 폴더 생성
def createFolder(request, pk):
    if request.method == "POST":
        folderName = request.POST.get("createFolderName")

        if len(folderName) > 0:
            duplicated_folder = Folder.objects.filter(folderName=folderName, parent_id=pk if pk != 0 else None)

            # 폴더 생성
            if len(duplicated_folder) == 0:
                folder = Folder(
                    userName=request.user,
                    folderName=folderName,
                    parent_id=pk if pk != 0 else None,
                )
                folder.save()

            # 같은 폴더에 이름 중복된 폴더 예외 처리
            elif len(duplicated_folder) >= 1:
                print("중복된 폴더 존재")

                # 이름 입력 안함 예외 처리
        elif len(folderName) == 0:
            print("이름을 입력해 주세요")

    return redirect("devbox:changeDirectory", pk)


# 파일 및 폴더 삭제
@csrf_exempt
def deleteFileAndFolder(request, pk):
    if request.method == "POST":
        selected_folder = request.POST.getlist("selected_folder")
        selected_file = request.POST.getlist("selected_file")

        # 파일 및 폴더 선택 안함 예외 처리
        if len(selected_file) == 0 and len(selected_folder) == 0:
            print("삭제할 파일을 선택해 주세요")

        # 삭제
        else:
            # 선택한 폴더 삭제
            if len(selected_folder) >= 1:
                for folder_id in selected_folder:
                    deletedFolder = RecycleBins(
                        deletedFolderID_id=folder_id,
                    )
                    deletedFolder.save()

            # 선택한 파일 삭제
            if len(selected_file) >= 1:
                for file_id in selected_file:
                    deletedFile = RecycleBins(
                        deletedFileID_id=file_id,
                    )
                    deletedFile.save()

    return redirect("devbox:changeDirectory", pk)


# 파일 및 폴더 이름 수정
@csrf_exempt
def renameFileAndFolder(request, pk):
    if request.method == "POST":
        selected_folder = request.POST.getlist("selected_folder")
        selected_file = request.POST.getlist("selected_file")
        rename = request.POST.get("renameFileAndFolderName")

        # 파일 및 폴더 선택 안함 예외 처리
        if len(selected_file) == 0 and len(selected_folder) == 0:
            print("이름을 변경할 파일을 선택해 주세요")

        # 이름 입력 안함 예외 처리
        elif len(rename) == 0:
            print("수정할 이름을 입력해 주세요")

        # 이름 수정
        else:
            # 선택한 폴더 이름 수정
            if len(selected_folder) >= 1:
                for folder_id in selected_folder:
                    folder = Folder.objects.get(id=folder_id)
                    folder.folderName = rename
                    folder.save()

            # 선택한 파일 이름 수정
            if len(selected_file) >= 1:
                rename = rename.split('.')
                for file_id in selected_file:
                    file = Files.objects.get(id=file_id)
                    newFileName = rename[0]
                    extension = file.fileName.split('.')[-1] if len(rename) == 1 else rename[-1]
                    file.fileName = f"{newFileName}.{extension}"
                    file.save()

    return redirect("devbox:changeDirectory", pk)


# 파일 정렬
def sortFileAndFolder(request, pk):
    template = 'home.html'
    if request.method == "GET":
        sortMode = request.GET.get('sortFileAndFolder')
        files = Files.objects.filter(parent_id=pk if pk != 0 else None)
        folders = Folder.objects.filter(parent_id=pk if pk != 0 else None)

        context = sort(sortMode, files, folders)
        context["current_folder_id"] = pk
        context["parentFolders"] = get_parent_folder_name(pk)
        return render(request, template, context=context)
    else:
        return render(request, template)

devbox/templates/devbox/detail.html
<!DOCTYPE html>
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>DevBox</title>
</head>
<body>
  <h2>{{file.fileName}}</h2>
  <h2>{{file.dataTimeOfUpload}}</h2>
  <form method="POST">
    <div>
      <input
        type="submit"
        value="다운로드"
        formaction="{% url
    'devbox:downloadFile' current_folder_id %}"
      />
    </div>
  </form>
</body>

devbox/templates/devbox/mail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DevBox</title>
    <style>
      * {
        font-family: "Roboto";
      }

      body {
        background-color: #f5f5f5;
      }
    </style>
  </head>

  <body>
    <h1>안녕하세요! DEVbox에서 파일을 확인해보세요</h1>
    <p><a href="{% url 'devbox:detail' file.id %}">{{link}}</a></p>
    <!--수정필요-->
  </body>
</html>

devbox/templates/devbox/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DevBox</title>
    <style>
        * {
            font-family: "Roboto";
        }

        body {
            background-color: #F5F5F5;
        }

        form {
            background-color: #FFFFFF;
            padding: 25px;
        }

        table {
            width: 100%;
            text-align: center;
            margin-top: 25px;
            padding: 25px;
            background-color: #FFFFFF;
        }

        table tr td {
            padding-top: 15px; 
        }
    </style>
    <link
    rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
  />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
    <div>
        <span id="share-link"></span>
    </div>
    <form action = "{% url 'devbox:search'%}" method="GET">
        <input name='search_input' type='text' placeholder="검색할 내용을 입력하세요" required>
        <button type='submit'>검색</button>
    </form>
    
    <form action="{% url 'devbox:uploadFile' current_folder_id %}" method="POST" enctype="multipart/form-data">
        <label for="uploadFile"> 파일 업로드
            <input type="file" id="uploadFile" name="uploadFile" multiple>
            {% csrf_token %}
            <input type="submit" value="UploadFile">
        </label>
    </form>

    <form action="{% url 'devbox:createFolder' current_folder_id %}" method="POST">
        <label for="createFolder"> 폴더 생성
            <input type="text" id="createFolder" name="createFolderName">
            {% csrf_token %}
            <input type="submit" value="CreateFolder">
        </label>
    </form>

    <form method="GET" action="{% url 'devbox:sortFile' current_folder_id %}">
        <div class="col-4">
          <select id="sort" name="sort">
            <option value="title" , name="title">이름순</option>
            <option value="size" ,name="size">크기순</option>
            <option value="recent" ,name="recent">최신순</option>
          </select>
          <button class="btn btn-primary" type="submit">정렬</button>
        </div>
      </form>

      <div
        class="modal fade"
        id="myModal"
        tabindex="-1"
        role="dialog"
        aria-labelledby="myModalLabel"
      >
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button
                type="button"
                class="close"
                data-dismiss="modal"
                aria-label="Close"
              >
                <span aria-hidden="true">&times;</span>
              </button>
              <h4 class="modal-title" id="myModalLabel">공유하기</h4>
              <input type="textarea" id="copylink" style="width:500px"/>
            </div>
            <div class="modal-body">
              <h4>이메일/사용자</h4>
              <label
                ><input type="radio" name="mode" value="email" checked />email
              </label>
              <label
                ><input type="radio" name="mode" value="user" />user Id
              </label>
              <h4>액세스 권한</h4>
              <label
                ><input type="radio" name="access" value="public" checked />누구나
              </label>
              <label
                ><input type="radio" name="access" value="private" />지정한 사람만
              </label>
              <h4>링크 만료기간</h4>
              <label><input type="time" min="00:00" max="24:00" /> </label>
              <h4>다운로드</h4>
              <label
                ><input
                  type="radio"
                  name="download"
                  value="possible"
                  checked
                />가능
              </label>
              <label
                ><input type="radio" name="download" value="impossible" />불가능
              </label>
            </div>
              <div class="modal-footer">
                <form method="POST" action="{% url 'devbox:mailing'%}">
                  <input name="email_address" id="email_address" type="email" multiple placeholder="이메일을 입력하세요" required>
                  {% csrf_token %}
                  <input type="textarea" id="selected_target" name="selected_target"/>
                  <button class="btn btn-primary" type="submit">
                    email로 보내기
                  </button>
                </form>
                <button class="btn btn-primary" type="submit" data-dismiss="modal">
                  사용자에게 보내기
                </button>
                <button type="button" class="btn btn-default" data-dismiss="modal">
                  닫기
                </button> 
              </div>
          </div>
        </div>
      </div>

    <form method="POST">
        <div>
            <input type="submit" value="다운로드" formaction="{% url 'devbox:downloadFile' current_folder_id %}"/>
            <input type="submit" value="삭제" formaction="{% url 'devbox:deleteFileAndFolder' current_folder_id %}"/>
        </div>

        <div>
            <label for="renameFileandFolder">
                <input type="text" id="renameFileandFolder" name="renameFileAndFolderName">
                {% csrf_token%}
                <input type="submit" value="수정" formaction="{% url 'devbox:renameFileAndFolder' current_folder_id %}"/>
            </label>
        </div>

        <table>
            <tr>
                <th>check</th>
                <th>ID</th>
                <th>Title</th>
                <th>File Path</th>
                <th>File Size</th>
                <th>Upload Date & Time</th>
                <th>share</th>
            </tr>

            {% for folder in folders %}
            <tr>
                <td><label><input type="checkbox" name="selected_folder" value="{{ folder.id }}"></label></td>
                <td>{{ folder.id }}</td>
                <td><a href="{% url 'devbox:changeDirectory' folder.id %}">{{ folder.get_foldername }}</a></td>
                <td>/{{ folder.id }}/</td>
                <td></td>
                <td>{{ folder.dateTimeOfUpload }}</td>
                <!--data-target : 모달 이름, data-sharetarget : 쉐어할 폴더 작성--> 
                <td><type="button"
                  class="btn btn-primary"
                  data-toggle="modal"
                  data-target="#myModal"
                  data-sharetarget="{{ folder.uuid }}">공유</button></td>
            </tr>
            {% endfor %}

            {% for file in files %}
            <tr>
                <td><label><input type="checkbox" name="selected_file" value="{{ file.id }}"></label></td>
                <td>{{ file.id }}</td>
                <td><a href="{% url 'devbox:detail' file.id %}">{{ file.fileName }}</a></td>
                <td>{{ file.uploadedFile.url }}</td>
                <td>{{ file.fileSize|filesizeformat }}</td>
                <td>{{ file.dateTimeOfUpload }}</td>
                <td><type="button"
                  class="btn btn-primary"
                  data-toggle="modal"
                  data-target="#myModal"
                  data-sharefile="{{ file.uuid }}">공유</button></td>
            </tr>
            {% endfor %}
        </table>
        <ul class="pagination justify-content-center">
          {% if page.has_previous %}
            <li calss="page item">
              <a class="page-link" 
                 href="?page={{page.previous_page_number}}">
                  이전
              </a>
            </li>
          {% else %}
          <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                이전
            </a>
          </li>
          {% endif %}
          {% for page_number in page.paginator.page_range %}
              {% if page_number == page.number %}
              <li calss="page-item active" aria-current="page">
                <a class="page-link" href="?page={{page_number}}">
                  {{page_number}}
                </a>
              </li>
              {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{page_number}}">
                  {{page_number}}
                </a>
              </li>
              {% endif %}
          {% endfor %}
          {% if page.has_next %}
          <li class="page-item">
            <a class="page-link"
               href="?page={{page.next_page_number}}">
                다음  
            </a>
          </li>
          {% else %}
          <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
              다음
            </a>
          </li>
          {% endif %}
         </ul> 
        </div>
    </form>
</body>
<script>
  let copyLink = document.getElementById("copylink");
  let emailAddress=document.getElementById("email_address");

  $(document).ready(function(){
    $('#myModal').on('show.bs.modal',function(event){
      var button = $(event.relatedTarget)
      var target_item = button.data('sharetarget');
      var target_itemFL = button.data('sharefile');
      const blockText = document.getElementById("selected_target");
      if(!target_itemFL){
        blockText.value="127.0.0.1:8000/sh/"+target_item;
        copyLink.value="127.0.0.1:8000/sh/"+target_item;
        blockText.style.display='None';
      }else{
        blockText.value="127.0.0.1:8000/s/"+target_itemFL;
        copyLink.value="127.0.0.1:8000/s/"+target_itemFL;
        blockText.style.display='None';
      }

      $("input[name='mode']").change(function(){
        if($(this).is(':checked')&&$(this).val()=='email'){
          emailAddress.style.display="Block";
        }
        if($(this).is(':checked')&&$(this).val()=='user'){
          emailAddress.style.display="None";
        }
      });

    })
  })
</script>
</html>

devbox/templates/devbox/recyclebin.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">-->
    <!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>-->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet">
        <title>DevBox</title>
        <style>

          body {
            background-color: #f5f5f5;
            font-family: 'Jua', sans-serif;
          }

          form {
            background-color: #ffffff;
            padding: 25px;
          }

          table {
            width: 100%;
            text-align: center;
            margin-top: 25px;
            padding: 25px;
            background-color: #ffffff;
          }

          table tr td {
            padding-top: 15px;
          }
        </style>
    </head>

    <body>
        <a href="{% url 'devbox:home' %}">home</a>
        <form method="POST">
            <div>
                <!-- 복구 -->
                {% csrf_token%}
                <input type="submit" value="복구" formaction="{% url 'devbox:restore' current_folder_id %}"/>
                <!-- 삭제 -->
                <input type="submit" value="영구삭제" formaction="{% url 'devbox:permanentDelete' current_folder_id %}"/>

            </div>

            <a href="{% url 'devbox:recyclebinDisplay' %}">root</a>
            {% for p_folder in parentFolders %}
            > <a href="{% url 'devbox:changeDirectoryInRecyclebin' p_folder.id %}"> {{p_folder.folderName}} </a>
            {% endfor %}

            <table>
                <tr>
                  <th>check</th>
                  <th>Title</th>
                  <th>File Size</th>
                  <th>Upload Date & Time</th>
                </tr>

                {% if folders %}
                {% for folder in folders %}
                <tr>
                    <td><label><input type="checkbox" name="selected_folder" value="{{ folder.id }}"/></label></td>
                    <td><a href="{% url 'devbox:changeDirectoryInRecyclebin' folder.id %}">{{ folder.get_foldername }}</a></td>
                    <td></td>
                    <td>{{ folder.dateTimeOfUpload | date:'Y-m-d h:i A' }}</td>
                </tr>
                {% endfor %}
                {% endif %}

                {% if files %}
                {% for file in files %}
                <tr>
                    <td><label><input type="checkbox" name="selected_file" value="{{ file.id }}"/></label></td>
                    <td>{{ file.fileName }}</td>
                    <td>{{ file.fileSize | filesizeformat }}</td>
                    <td>{{ file.dateTimeOfUpload | date:'Y-m-d h:i A' }}</td>
                </tr>
                {% endfor %}
                {% endif %}
            </table>
        </form>
    </body>
</html>

devbox/templates/devbox/share_folder_link.html
{% if option=='folder' %}
<h1><a href="{% url 'devbox:shared_forder' uuid %}">{{address}}</a></h1>
{% else %}
<h1><a href="{% url 'devbox:shared_file' uuid %}">{{address}}</a></h1>
{% endif %}