apis/urls.py
from django.urls import path
from apis.v1 import UserCreateView, UserLoginView, UserLogoutView, UserGetView, RelationCreateView, RelationDeleteView

urlpatterns = [    
    path('v1/users/login/', UserLoginView.as_view(), name='apis_v1_user_login'),
    path('v1/users/logout/', UserLogoutView.as_view(), name='apis_v1_user_logout'),
    path('v1/users/create/', UserCreateView.as_view(), name='apis_v1_user_create'),
    path('v1/users/get/', UserGetView.as_view(), name='apis_v1_user_get'),
    path('v1/relations/create/', RelationCreateView.as_view(), name='apis_v1_relation_create'),
    path('v1/relations/delete/', RelationDeleteView.as_view(), name='apis_v1_relation_delete'),
]

config/urls.py
from pipes import Template
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.conf import settings

from contents.views import HomeView, RelationView
from apis.v1 import RelationCreateView
from contents.models import Status

admin.site.site_header = "DevBox Admin"
admin.site.site_title = "DevBox Admin Site"
admin.site.index_title = "Hello everyone:)"
admin.site.register(Status)


class NonUserTemplateView(TemplateView):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_anonymous:
            return redirect('contents_home')
        return super(NonUserTemplateView, self).dispatch(request, *args, **kwargs)
    

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', HomeView.as_view(), name='contents_home'),
    path('login/', NonUserTemplateView.as_view(template_name='login.html'), name='login'),
    path('register/', NonUserTemplateView.as_view(template_name='register.html'), name='register'),
    path('relation/', RelationView.as_view(), name='contents_relation'),
    
    path('apis/', include('apis.urls')),
    path("home/", include('devbox.urls')),
]


urlpatterns += [
    path('accounts/', include('allauth.urls'))
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

devbox/urls.py
from .Views import views, searchViews, deleteViews, mailingViews
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

app_name = "devbox"

urlpatterns = [
    path("", login_required(views.home), name="home"),  # home directory
    path("<int:pk>/", views.change_directory,
         name="changeDirectory"),  # 디렉토리 이동

    path("uploadFile/<int:pk>/", views.uploadFile, name="uploadFile"),  # 파일 업로드
    path("downloadFile/<int:pk>/", views.downloadFile,
         name="downloadFile"),  # 파일 다운로드
    path("createFolder/<int:pk>/", views.createFolder,
         name="createFolder"),  # 폴더 생성
    path("deleteFileAndFolder/<int:pk>/", views.deleteFileAndFolder,
         name="deleteFileAndFolder"),  # 파일 및 폴더 삭제
    path("renameFileAndFolder/<int:pk>/", views.renameFileAndFolder,
         name="renameFileAndFolder"),  # 파일 및 폴더 이름 수정
    path("sortFileAndFolder/<int:pk>/", views.sortFileAndFolder,
         name="sortFileAndFolder"),  # 파일 정렬

    path("search/", login_required(searchViews.searchFileAndFolder), name="search"),
    path("sh/<uuid:uuid>/", mailingViews.display_file_and_folder_ui, name='shared'),
    path("s/<uuid:uuid>/", mailingViews.display_file_and_folder_ui,
         name='shared_file'),  # 파일 공유
    path("mailing/", mailingViews.mailing, name="mailing"),  # 메일링

    path("recyclebin/", deleteViews.recyclebin,
         name="recyclebinDisplay"),  # 휴지통
    path("recyclebin/<int:pk>", deleteViews.changeDirectoryInRecyclebin,
         name="changeDirectoryInRecyclebin"),  # 휴지통 내 폴더 이동
    path("restore/<int:pk>", deleteViews.restore, name="restore"),  # 파일 및 폴더 복구
    path("permanentDelete/<int:pk>", deleteViews.permanentDelete,
         name="permanentDelete"),  # 파일 및 폴더 영구
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

django_base/django_base/urls.py
from pipes import Template
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.conf import settings

from contents.views import HomeView, RelationView

admin.site.site_header = "Fastgram Admin"
admin.site.site_title = "Fastgram Admin Site"
admin.site.index_title = "Hello everyone:)"


class NonUserTemplateView(TemplateView):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_anonymous:
            return redirect('contents_home')
        return super(NonUserTemplateView, self).dispatch(request, *args, **kwargs)
    

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', HomeView.as_view(), name='contents_home'),
    path('login/', NonUserTemplateView.as_view(template_name='login.html'), name='login'),
    path('register/', NonUserTemplateView.as_view(template_name='register.html'), name='register'),
    path('relation/', RelationView.as_view(), name='contents_relation'),
    path('apis/', include('apis.urls')),
]


urlpatterns += [
    path('accounts/', include('allauth.urls'))
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static '/css/main.css' %}">
  <link rel="stylesheet" href="{% static '/css/register.css' %}">
  <link rel="stylesheet" href="{% static '/css/style.css' %}">
  <link rel="stylesheet" href="{% static '/css/login.css' %}">
  <!-- Font Awesome -->
  <script src="https://kit.fontawesome.com/596cc0eddc.js" crossorigin="anonymous"></script>
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'css/bower_components/Ionicons/css/ionicons.min.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link href="{% static '/css/adminLTE.css' %}" rel="stylesheet">
  <title>{% block title %}{% endblock %}</title>
  {% block head %}
  {% endblock %}
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

templates/header.html
{% extends 'base.html' %}
{% block body %}
<nav class="fast-nav navbar navbar-expand-lg navbar-light bg-white">
        <a class="navbar-brand text-danger col-sm-8" href="{% url 'contents_home' %}"><b>Devbox</b></a>
        <div class="collapse navbar-collapse col-sm-4" id="navbarText" style="display: inline-block !important; text-align: right;">
          <span class="navbar-text col-sm-3">
            {{ request.user }}
          </span>
          <span class="navbar-text col-sm-3">
            <a href="{% url 'contents_relation' %}">친구목록</a>
          </span>
          <span class="navbar-text col-sm-3">
            <a href="javascript:void(0);" id="logout">로그아웃</a>
          </span>
        </div>
</nav>
{% endblock %}

templates/home_2.html
{% extends "base.html" %}

{% block head %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/dropzone@5.5.1/dist/dropzone.min.css">
{% endblock %}

{% block body %}
  <script>
      setTimeout(function() {window.location.href="/home"},0)
  </script>
{% endblock %}

templates/mail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DevBox</title>
    <style>
        * {
            font-family: "Roboto";
        }

        body {
            background-color: #F5F5F5;
        }
    </style>
</head>

<body>
    <h1>안녕하세요! DEVbox에서 파일을 확인해보세요</h1>
    <p>{{link}}</p>
</body>
</html>

templates/recyclebin.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <title>Devbox</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Open+Sans&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Josefin+Sans:ital,wght@1,700&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap');
    @import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css');

    * {
      list-style: none;
      text-decoration: none;
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      font-family: 'Apple SD Gothic Neo', sans-serif;
    }

    body {
      background: #f5f6fa;
    }

    .wrapper .sidebar {
      background:
        linear-gradient(135deg, #7780E0, #90B4F7, transparent);
      position: fixed;
      width: 17%;
      height: 100%;
      padding: 20px 0;
      float: left;
    }

    .wrapper .sidebar .devbox {
      text-align: center;
    }

    .wrapper .sidebar .devbox .title{
      border: 0;
      background-color:transparent;
    }

    .wrapper .sidebar .devbox .title .main_btn{
      margin: 25px 5px 35px 0px;
      width: 75%;
      height: 80px;
    }

    .wrapper .sidebar ul li a {
      display: block;
      padding: 16px 35px;
      border-bottom: 1px solid #f1eded;
      color: #f1eded;
      font-size: 16px;
      letter-spacing: 1.5px;
      position: relative;
    }

    .top_line {
      border-top: 1px solid #f1eded;
    }

    .wrapper .sidebar ul li a .icon {
      color: #dee4ec;
      width: 35px;
      display: inline-block;
    }

    .wrapper .sidebar ul li a:hover,
    .wrapper .sidebar ul li a.active {
      color: #7780E0;

      background: white;
      border-right: 2px solid #BABEE0;
    }

    .wrapper .sidebar ul li a:hover .icon,
    .wrapper .sidebar ul li a.active .icon {
      color: #7780E0;
    }

    .wrapper .sidebar ul li a:hover:before,
    .wrapper .sidebar ul li a.active:before {
      display: block;
    }

    .wrapper .sidebar .item {
      font-weight: 500;
      font-size: 19px;
      font-family: Pretendard, -apple-system, BlinkMacSystemFont, system-ui, Roboto, 'Helvetica Neue', 'Segoe UI', 'Apple SD Gothic Neo', 'Noto Sans KR', 'Malgun Gothic', sans-serif;
    }

    .main {
      width: 80%;
      height: 100%;
      padding: 20px 0;
      float: right;
    }

    .header {
      width: 99%;
      margin-bottom: 70px;
      font-weight: 500;
      font-size: 14.5px;
      font-family: Pretendard, -apple-system, BlinkMacSystemFont, system-ui, Roboto, 'Helvetica Neue', 'Segoe UI', 'Apple SD Gothic Neo', 'Noto Sans KR', 'Malgun Gothic', sans-serif;
    }

    .header_right {
      float: right;
      margin: 5px 35px 50px 0px;
    }

    .logout {
      float: right;
      margin: 0px 0px 0px 40px;
      border: none;
      width: 90px;
      height: 40px;
      border-radius: 5px;
      background: #282862;
      color: white;
      font-weight: 800;
      font-family: "Noto Sans KR", sans-serif;
      box-shadow: 0px 2px 5px #cedfff;
    }

    .logout:focus {
      outline: none;
    }

    .middle {
      display: flex;
      justify-content: space-between;
      align-items: center;
      width: 98%;
      margin:0px 20px -20px 10px;
    }

    .middle_left {
    float: left;
    margin: 10px 100px -5px -25px;
    }

    .root_font {
    opacity: 0.8;
    font-weight: 550;
    font-size: 20px;
    font-family: Pretendard, -apple-system, BlinkMacSystemFont, system-ui, Roboto, 'Helvetica Neue', 'Segoe UI', 'Apple SD Gothic Neo', 'Noto Sans KR', 'Malgun Gothic', sans-serif;
    }
    a {
    color: #555BA1;
    text-decoration: none;
    }

    .middle_right {
    float: right;
    margin-bottom: 10px;
    margin-top: 10px;
    margin-right:  10px;
    }

    .btns {
      display: flex;
      justify-content: space-between;
    }

    .btn {
      border: none;
      width: 90px;
      height: 40px;
      border-radius: 5px;
      background-color: transparent;
      font-weight: 700;
      font-size: 16.5px;
      font-family: Pretendard, -apple-system, BlinkMacSystemFont, system-ui, Roboto, 'Helvetica Neue', 'Segoe UI', 'Apple SD Gothic Neo', 'Noto Sans KR', 'Malgun Gothic', sans-serif;
      letter-spacing: 1.5px;
      box-shadow: 0px 0px 5px #cacaca;
      margin-right: 8px;
      opacity: 0.9;
    }

    .btn:focus {
      outline: none;
    }

    hr {
      position: relative;
      top: 38px;
      width: 1100px;
    }

    .hr1 {
      border-top: 1px solid #f1eded;
      color: #f1eded;
      position: relative;
    }

    .table {
      display: flex;
      flex-direction: column;
      border: none;
      width: 99%;
      height: 100vh;
      border-radius: 5px;
      box-shadow: 0px 0px 5px #cacaca;
      padding: 22px 30px 25px 30px;
      margin: 23px 20px 10px -20px;
      line-height: 35px;
    }

    .input_table {
      font-weight: 540;
      font-size: 16.5px;
      font-family: Pretendard, -apple-system, BlinkMacSystemFont, system-ui, Roboto, 'Helvetica Neue', 'Segoe UI', 'Apple SD Gothic Neo', 'Noto Sans KR', 'Malgun Gothic', sans-serif;
      letter-spacing: 0px;
      opacity: 0.85;
    }

    .table-columns {
      display: flex;
    }

    .table-row-item {
      display: flex;
      padding: 10px 0px;
      align-items: center;
    }

    .clicked {
      background-color: #e8f0fe;
    }

    .table-columns {
      width: 100%;
    }

    .table-column-check,
    .table-row-check {
      width: 100px;
    }

    .table-row-check {
      padding-left: 15px;
    }

    .table-column-name,
    .table-row-name {
      width: 530px;
    }

    .table-column-date,
    .table-row-date {
      width: 330px;
    }

    .table-column-size,
    .table-row-size {
      width: 180px;
    }

    .table-rows {
      overflow: auto;
      height: 100%;
    }

    th,
    td {
      padding: 5px;
      text-align: center;
      border-bottom: 0.5px solid #E0E0E0;
    }

    .upload-input {
      display: none;
    }
  </style>
</head>

<body>
  <!--모달 부분 (여기는 로직 수정 X, 디자인 수정 필요 O)-->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="myModalLabel">공유하기</h4>
          <input type="textarea" id="copylink" style="width:500px" />
        </div>
        <div class="modal-body">
          <h4>이메일/사용자</h4>
          <label><input type="radio" name="mode" value="email" checked />email</label>
          <label><input type="radio" name="mode" value="user" />user Id</label>
          <h4>액세스 권한</h4>
          <label><input type="radio" name="access" value="public" checked />누구나</label>
          <label><input type="radio" name="access" value="private" />지정한 사람만</label>
          <h4>링크 만료기간</h4>
          <label><input type="time" min="00:00" max="24:00" /> </label>
          <h4>다운로드</h4>
          <label><input type="radio" name="download" value="possible" checked />가능</label>
          <label><input type="radio" name="download" value="impossible" />불가능</label>
        </div>
        <div class="modal-footer">
          <form method="POST">
            <input name="email_address" id="email_address" type="email" multiple placeholder="이메일을 입력하세요" required>
            {% csrf_token %}
            <input type="textarea" id="selected_target" name="selected_target" />
            <button class="btn btn-primary" type="submit">
              email로 보내기
            </button>
          </form>
          <button class="btn btn-primary" type="submit" data-dismiss="modal">
            사용자에게 보내기
          </button>
          <button type="button" class="btn btn-default" data-dismiss="modal">
            닫기
          </button>
        </div>
      </div>
    </div>
  </div>
  <!--모달 부분 끝 -->

  <div class="wrapper">
    <div class="sidebar">
      <div class="devbox">
        <a href="{% url 'contents_home' %}" class="title"><img class="main_btn"
            src="{%static 'KakaoTalk_20220601_145619966_01.png' %}"></a>
      </div>

      <div>
        <ul>
          <li>
            <div class="hr1"></div>
            <a class="item" href="{% url 'contents_home' %}">
              <span class="icon"><i class="fas fa-home"></i></span>내 파일
            </a>
          </li>
          <li>
            <a class="item active" href="{% url 'devbox:recyclebinDisplay' %}">
              <span class="icon"><i class="fas fa-trash"></i></span>휴지통
            </a>
          </li>
        </ul>
      </div>
    </div>

    <div class="main">
      <div class="header">
        <div class="header_right">
          <span>{{ request.user }}님 안녕하세요!</span>
          <a>&nbsp&nbsp&nbsp</a>
          <a href="{% url 'contents_relation' %}">친구목록</a>
          <a>&nbsp&nbsp&nbsp</a>
          <a href="javascript:void(0);" id="logout">로그아웃</a>
        </div>
      </div>

      <form method="POST">
        <div class="middle">
          <div class="middle_left root_font">
            <!-- directory -->
              <a href="{% url 'devbox:home' %}">root</a>
              {% for p_folder in parentFolders %}
              <span class="root_font">></span> <a href="{% url 'devbox:changeDirectory' p_folder.id %}"> {{p_folder.folderName}} </a>
              {% endfor %}
          </div>
          <div class="middle_right">
            <div class="btns">
              <!-- 복구 -->
              {% csrf_token%}
              <input type="submit" class="btn" value="복구" formaction="{% url 'devbox:restore' current_folder_id %}" />
              <!-- 삭제 -->
              {% csrf_token%}
              <input type="submit" class="btn" value="영구삭제"
                formaction="{% url 'devbox:permanentDelete' current_folder_id %}" />
            </div>
          </div>
        </div>

        <div class="table">
          <div class="input_table">
            <table>
              <tr>
                <th class="table-column-check">선택</th>
                <th class="table-column-name">파일 이름</th>
                <th class="table-column-date">업로드 날짜</th>
                <th class="table-column-size">파일 크기</th>
              </tr>

              {% if folders %}
              {% for folder in folders %}
              <tr>
                <td><label><input type="checkbox" name="selected_folder" value="{{ folder.id }}" /></label></td>
                <td><a href="{% url 'devbox:changeDirectoryInRecyclebin' folder.id %}">{{ folder.get_foldername }}</a>
                </td>
                <td>{{ folder.dateTimeOfUpload | date:'Y-m-d h:i A' }}</td>
                <td></td>
              </tr>
              {% endfor %}
              {% endif %}

              {% if files %}
              {% for file in files %}
              <tr>
                <td><label><input type="checkbox" name="selected_file" value="{{ file.id }}" /></label></td>
                <td>{{ file.fileName }}</td>
                <td>{{ file.dateTimeOfUpload | date:'Y-m-d h:i A' }}</td>
                <td>{{ file.fileSize | filesizeformat }}</td>
              </tr>
              {% endfor %}
              {% endif %}
            </table>
          </div>
        </div>
      </form>
    </div>
  </div>
</body>

<script>
      const logout = document.getElementById("logout")
      logout.addEventListener('click',()=>{
        window.location.href="http://127.0.0.1:8000/apis/v1/users/logout/"
        location.reload()
      })

</script>

</html>

templates/register.html
     

<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,
    initial-scale=1.0" />
    <script src="https://kit.fontawesome.com/596cc0eddc.js" crossorigin="anonymous"></script>
    <title>Devbox</title>
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@700&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Open+Sans&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Josefin+Sans:ital,wght@1,700&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap');

html {
  width: 100%;
  height: 100%;
}

hr {
  position: relative;
  top: 15px;
  width: 100px; 

}

body {
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  position: relative;
}

.jb {
    margin: 0px auto;
    width: 100%;
    height: 100vh;
    background: 
    linear-gradient(135deg,#EC9999, #D8E7FC, transparent),
    linear-gradient(300deg,#F1AD3F, transparent);
    background-blend-mode: sreen;
    positon :relative;
}

.jb2{
    margin: 0px auto;
    width: 100%;
    height: 100vh;
    background: 
    radial-gradient(circle closest-corner at 40% 10%,#90B4F7,transparent),
    radial-gradient(circle closest-corner at 63% 94%,#D54F52, transparent),
    radial-gradient(circle closest-corner at 80% 5%,#D8E7FC, transparent),
    radial-gradient(circle closest-corner at 90% 5%,#D8E7FC, transparent),
    radial-gradient(circle closest-corner at 15% 90%,#D8E7FC, transparent);
    background-blend-mode: sreen;
    position: absolute;
}

.logo {
position : fixed;
left:0;
top: 0;
margin-top: 2%;
margin-left: 2%;
width: 10%;
height: 8%;
opacity: 0.9;
}

main {
display: flex;
width: 1180px;
height: 550px;
border-radius: 20px;
position: absolute;
-moz-box-shadow: 0 0 4px #F7FFFF;
-webkit-box-shadow: 0 0 4px #F7FFFF;
box-shadow: 0px 0px 4px #F7FFFF;
opacity: 0.84;
}

.left {
background: #C7D7F9;
width: 55%;
height: 100%;
display: flex;
align-items: center;
border-radius: 20px 0px 0px 20px;
}

.people {
margin:50px 0px 0px -10px;
width: 725px;
height: 520px;
}

.title {
  font-size: 40px;  
  font-weight: 1000;
  font-family: 'GangwonEduPowerExtraBoldA';
  text-shadow: 3px 5px 5px #adaccd;
  color: #282862;
  margin-top: 70px;
  margin-bottom: 50px;
  text-align: center;
}

.container {
  width: 294px;
  height: 38px;
  margin: 20px 120px 15px;
  border: 1.5px solid #cacaca;
  background-color: transparent;
  border-radius: 5px;
  box-shadow: 0px 0px 4px #cacaca;
}

.input_container {
  margin-top: 9px;
  margin-left: 12px;
  border: none;
  color: #282862;
  font-weight: 700;
  font-size: 14.5px;
  font-family: "Noto Sans KR", sans-serif;
  opacity: 0.9;
}
.input_container i{
    color: #282862;
    margin: 2px;
    opacity: 0.8;
}
.input_container input{
    background: none;
    border: none;
    padding-left: 6px;
    width:240px;
}
.input_contanier input:focus{
    outline: none;
}

.right {
border-radius: 0px 20px 20px 0px;
background: #FFFFFF;
width: 45%;
height: 100%;
text-align: center;
}

.btn_signup {
  width: 298px;
  height: 40px;
  margin: 20px 120px 0px;
  border-radius: 5px;
  border: 0;
  outline: none;
  background: #282862;
  margin-top: 25px;
  font-weight: 800;
  font-size: 15px;
  font-family: "Noto Sans KR", sans-serif;
  color: #FFFFFF;
  text-align: center;
}


    </style>
  </head>
</html>


<body>
    <div class="jb"></div>
    <div class="jb2"></div> 
    <img class="logo" src="{%static 'KakaoTalk_20220601_145619966_01.png' %}">

    <main>
      <div class="left">
        <img class="people" src="{%static 'KakaoTalk_20220601_145619966.png' %}">
      </div>

      <div class="right"> 
        <div class="title">Sign Up</div>

        <div class="container">
            <div class="input_container">
                <i class="fas fa-user"></i>
                <input placeholder="Id" type="text" id="username">
            </div>
        </div>

        <div class="container">
            <div class="input_container">
                <i class="fa-solid fa-envelope"></i>
                <input placeholder="Email" type="email" id="email">
            </div>
        </div>        


        <div class="container">
            <div class="input_container">
                <i class="fa-solid fa-lock"></i>
                <input placeholder="Password" type="password" id="password">
            </div>
        </div>    
        <button class="btn_signup" id="register">Create</button> 
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="crossorigin="anonymous"></script>
      </div>
    </main>

  <script>
$(document).ready(function () {
$('#register').click(function() {
    $.post('/apis/v1/users/create/', {'username': $('#username').val(), 'email': $('#email').val(), 'password': $('#password').val()}, function() {
        alert('가입을 환영합니다!');
        window.location = {% url 'login' %};
    }).fail(function(data) {
        alert(data.responseJSON.message);
    });
});
});
  </script>

</body>

templates/share_folder_link.html
{% if option=='folder' %}
<h1><a href="{% url 'devbox:shared_folder' uuid %}">{{address}}</a></h1>
{% else %}
<h1><a href="{% url 'devbox:shared_file' uuid %}">{{address}}</a></h1>
{% endif %}